export interface DesignPreview {
  slug: string;
  name: string;
  description: string;
  colors: { key: string; hex: string }[];
  fonts: { role: string; family: string }[];
  radius?: string;
  spacing?: string;
  shadow?: string;
  components?: string[];
}

export const designPreviews: DesignPreview[] = [
  {
    slug: "vercel",
    name: "Vercel-Inspired-design-analysis",
    description:
      "An inspired interpretation of Vercel's design language — a developer-platform brand whose surface is a stark black-and-ink duet on near-white canvas, broken at hero scale by a multi-color mesh gradient (cyan / blue / magenta / amber) that acts as the entire decorative system, paired with a custom geometric sans for headlines and a monospaced caption face for technical labels.",
    colors: [
      { key: "primary", hex: "#171717" },
      { key: "on-primary", hex: "#ffffff" },
      { key: "ink", hex: "#171717" },
      { key: "body", hex: "#4d4d4d" },
      { key: "mute", hex: "#888888" },
      { key: "hairline", hex: "#ebebeb" },
      { key: "hairline-strong", hex: "#a1a1a1" },
      { key: "canvas", hex: "#ffffff" },
      { key: "canvas-soft", hex: "#fafafa" },
      { key: "canvas-soft-2", hex: "#f5f5f5" },
      { key: "link", hex: "#0070f3" },
      { key: "link-deep", hex: "#0761d1" },
      { key: "link-bg-soft", hex: "#d3e5ff" },
      { key: "success", hex: "#0070f3" },
      { key: "error", hex: "#ee0000" },
      { key: "error-soft", hex: "#f7d4d6" },
      { key: "error-deep", hex: "#c50000" },
      { key: "warning", hex: "#f5a623" },
      { key: "warning-soft", hex: "#ffefcf" },
      { key: "warning-deep", hex: "#ab570a" },
      { key: "violet", hex: "#7928ca" },
      { key: "violet-soft", hex: "#d8ccf1" },
      { key: "violet-deep", hex: "#4c2889" },
      { key: "cyan", hex: "#50e3c2" },
      { key: "cyan-soft", hex: "#aaffec" },
      { key: "cyan-deep", hex: "#29bc9b" },
      { key: "highlight-pink", hex: "#ff0080" },
      { key: "highlight-magenta", hex: "#eb367f" },
      { key: "gradient-develop-start", hex: "#007cf0" },
      { key: "gradient-develop-end", hex: "#00dfd8" },
      { key: "gradient-preview-start", hex: "#7928ca" },
      { key: "gradient-preview-end", hex: "#ff0080" },
      { key: "gradient-ship-start", hex: "#ff4d4d" },
      { key: "gradient-ship-end", hex: "#f9cb28" },
      { key: "selection-bg", hex: "#171717" },
      { key: "selection-fg", hex: "#f2f2f2" },
    ],
    fonts: [
      { role: "display", family: "Geist, Inter, system-ui, -apple-system, sans-serif" },
      { role: "body", family: "Geist, Inter, system-ui, -apple-system, sans-serif" },
      { role: "mono", family: "Geist Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, monospace" },
    ],
    radius: "none: 0px; xs: 4px; sm: 6px; md: 8px; lg: 12px; xl: 16px; pill-sm: 64px; pill: 100px; full: 9999px",
    spacing: "xxs: 4px · xs: 8px · sm: 12px · md: 16px · lg: 24px · xl: 32px · 2xl: 40px · 3xl: 48px · 4xl: 64px · 5xl: 96px · 6xl: 128px · section: 192px",
    shadow: "0px 1px 1px #00000005, 0px 2px 2px #0000000a",
    components: [
      "nav-bar",
      "button-primary",
      "button-secondary",
      "card-marketing",
      "card-soft",
      "code-editor-mockup",
      "form-input",
      "badge-secondary",
      "hero-band",
      "feature-mesh-band",
      "showcase-band-dark",
      "footer",
    ],
  },
  {
    slug: "linear.app",
    name: "Linear-design-analysis",
    description:
      "A near-black product-focused marketing canvas built around #010102 (the deepest dark surface of any tool in this collection), light gray text (#f7f8f8), and the signature Linear lavender-blue (#5e6ad2) used as the single chromatic accent. The system reads as software-craft documentation: dense, technical, and quietly luxurious. Display type is set in the Linear custom sans (SF Pro Display fallback) at 500–700 with measured negative tracking. Cards live as charcoal panels (#0f1011) with hairline borders. The accent lavender appears on the brand mark, focus rings, and a few intentional CTAs — never decoratively. Page rhythm leans on product UI screenshots framed in dark panels rather than atmospheric color.",
    colors: [
      { key: "primary", hex: "#5e6ad2" },
      { key: "on-primary", hex: "#ffffff" },
      { key: "primary-hover", hex: "#828fff" },
      { key: "primary-focus", hex: "#5e69d1" },
      { key: "ink", hex: "#f7f8f8" },
      { key: "ink-muted", hex: "#d0d6e0" },
      { key: "ink-subtle", hex: "#8a8f98" },
      { key: "ink-tertiary", hex: "#62666d" },
      { key: "canvas", hex: "#010102" },
      { key: "surface-1", hex: "#0f1011" },
      { key: "surface-2", hex: "#141516" },
      { key: "surface-3", hex: "#18191a" },
      { key: "surface-4", hex: "#191a1b" },
      { key: "hairline", hex: "#23252a" },
      { key: "hairline-strong", hex: "#34343a" },
      { key: "hairline-tertiary", hex: "#3e3e44" },
      { key: "inverse-canvas", hex: "#ffffff" },
      { key: "inverse-surface-1", hex: "#f5f6f6" },
      { key: "inverse-surface-2", hex: "#f6f7f7" },
      { key: "inverse-ink", hex: "#000000" },
      { key: "brand-secure", hex: "#7a7fad" },
      { key: "semantic-success", hex: "#27a644" },
      { key: "semantic-overlay", hex: "#000000" },
    ],
    fonts: [
      { role: "display", family: "Linear Display" },
      { role: "body", family: "Linear Text" },
      { role: "mono", family: "Linear Mono" },
    ],
    radius: "xs: 4px; sm: 6px; md: 8px; lg: 12px; xl: 16px; xxl: 24px; pill: 9999px; full: 9999px",
    spacing: "xxs: 4px · xs: 8px · sm: 12px · md: 16px · lg: 24px · xl: 32px · xxl: 48px · section: 96px",
    shadow: "none",
    components: [
      "button-primary",
      "button-secondary",
      "button-tertiary",
      "pricing-card",
      "feature-card",
      "product-screenshot-card",
      "testimonial-card",
      "text-input",
      "status-badge",
      "top-nav",
      "cta-banner",
      "footer",
    ],
  },
  {
    slug: "stripe",
    name: "Stripi-Inspired-design-analysis",
    description:
      "An inspired interpretation of Stripi's design language — a financial-infrastructure brand built on a deep navy ink, an electric indigo primary, and a recurring atmospheric gradient mesh that occupies the upper third of nearly every marketing page. The system pairs the proprietary Sohne family at thin (300) weights with negative letter-spacing for editorial-density display headlines, and uses tabular-figure body type where money and numerics matter. Buttons are tight-radius pills, cards live on near-white surfaces, and the dashboard track flips polarity to a familiar dark-app shell.",
    colors: [
      { key: "primary", hex: "#533afd" },
      { key: "primary-deep", hex: "#4434d4" },
      { key: "primary-press", hex: "#2e2b8c" },
      { key: "primary-soft", hex: "#665efd" },
      { key: "primary-bg-subdued-hover", hex: "#b9b9f9" },
      { key: "brand-dark-900", hex: "#1c1e54" },
      { key: "ink", hex: "#0d253d" },
      { key: "ink-secondary", hex: "#273951" },
      { key: "ink-mute", hex: "#64748d" },
      { key: "ink-mute-2", hex: "#61718a" },
      { key: "on-primary", hex: "#ffffff" },
      { key: "canvas", hex: "#ffffff" },
      { key: "canvas-soft", hex: "#f6f9fc" },
      { key: "canvas-cream", hex: "#f5e9d4" },
      { key: "hairline", hex: "#e3e8ee" },
      { key: "hairline-input", hex: "#a8c3de" },
      { key: "ruby", hex: "#ea2261" },
      { key: "magenta", hex: "#f96bee" },
      { key: "lemon", hex: "#9b6829" },
      { key: "shadow-blue", hex: "#003770" },
    ],
    fonts: [
      { role: "display", family: "sohne-var, 'SF Pro Display', system-ui, -apple-system, sans-serif" },
      { role: "body", family: "sohne-var, 'SF Pro Display', system-ui, -apple-system, sans-serif" },
    ],
    radius: "xs: 4px; sm: 6px; md: 8px; lg: 12px; xl: 16px; pill: 9999px",
    spacing: "xxs: 2px · xs: 4px · sm: 8px · md: 12px · lg: 16px · xl: 24px · xxl: 32px · huge: 64px",
    shadow: "rgba(0,55,112,0.08) 0 8px 24px, rgba(0,55,112,0.04) 0 2px 6px",
    components: [
      "button-primary-pill",
      "button-secondary",
      "button-on-dark",
      "text-input",
      "card-feature-light",
      "card-pricing",
      "card-pricing-featured",
      "card-cream-band",
      "card-dashboard-mockup",
      "pill-tag-soft",
      "nav-bar-on-mesh",
      "footer-light",
    ],
  },
  {
    slug: "apple",
    name: "Apple-design-analysis",
    description:
      "A photography-first interface that turns marketing into a museum gallery. Edge-to-edge product tiles alternate light and dark canvases, framed by SF Pro Display headlines with negative letter-spacing and a single Action Blue (#0066cc) interactive color. UI chrome recedes so the product can speak — no decorative gradients, no shadows on chrome, only the one signature drop-shadow under product imagery resting on a surface.",
    colors: [
      { key: "primary", hex: "#0066cc" },
      { key: "primary-focus", hex: "#0071e3" },
      { key: "primary-on-dark", hex: "#2997ff" },
      { key: "ink", hex: "#1d1d1f" },
      { key: "body", hex: "#1d1d1f" },
      { key: "body-on-dark", hex: "#ffffff" },
      { key: "body-muted", hex: "#cccccc" },
      { key: "ink-muted-80", hex: "#333333" },
      { key: "ink-muted-48", hex: "#7a7a7a" },
      { key: "divider-soft", hex: "#f0f0f0" },
      { key: "hairline", hex: "#e0e0e0" },
      { key: "canvas", hex: "#ffffff" },
      { key: "canvas-parchment", hex: "#f5f5f7" },
      { key: "surface-pearl", hex: "#fafafc" },
      { key: "surface-tile-1", hex: "#272729" },
      { key: "surface-tile-2", hex: "#2a2a2c" },
      { key: "surface-tile-3", hex: "#252527" },
      { key: "surface-black", hex: "#000000" },
      { key: "surface-chip-translucent", hex: "#d2d2d7" },
      { key: "on-primary", hex: "#ffffff" },
      { key: "on-dark", hex: "#ffffff" },
    ],
    fonts: [
      { role: "display", family: "SF Pro Display, system-ui, -apple-system, sans-serif" },
      { role: "body", family: "SF Pro Text, system-ui, -apple-system, sans-serif" },
    ],
    radius: "none: 0px; xs: 5px; sm: 8px; md: 11px; lg: 18px; pill: 9999px; full: 9999px",
    spacing: "xxs: 4px · xs: 8px · sm: 12px · md: 17px · lg: 24px · xl: 32px · xxl: 48px · section: 80px",
    shadow: "rgba(0, 0, 0, 0.22) 3px 5px 30px 0",
    components: [
      "global-nav",
      "sub-nav-frosted",
      "button-primary",
      "button-secondary-pill",
      "button-dark-utility",
      "product-tile-light",
      "product-tile-parchment",
      "product-tile-dark",
      "store-utility-card",
      "configurator-option-chip",
      "search-input",
      "floating-sticky-bar",
      "footer",
    ],
  },
  {
    slug: "notion",
    name: "Notion-design-analysis",
    description:
      "Notion presents itself as the all-in-one workspace through a confident, illustration-rich brand voice — anchored by a deep navy hero band ({colors.brand-navy}) decorated with brand-colored sticky-note dots and mesh wire illustrations, a signature purple pill primary CTA ({colors.primary}), and a rich palette of pastel-tinted feature cards that echo the colorful database properties of the live product. The system uses a Notion-Sans (Inter-based) typeface across every UI surface, anchors a 4-tier pricing comparison (Free / Plus / Business / Enterprise), and presents the live workspace UI mockup directly inside the hero band. Coverage spans homepage, Enterprise, Product AI, Product Agents, Startups, and Pricing surfaces.",
    colors: [
      { key: "primary", hex: "#5645d4" },
      { key: "primary-pressed", hex: "#4534b3" },
      { key: "primary-deep", hex: "#3a2a99" },
      { key: "on-primary", hex: "#ffffff" },
      { key: "brand-navy", hex: "#0a1530" },
      { key: "brand-navy-deep", hex: "#070f24" },
      { key: "brand-navy-mid", hex: "#1a2a52" },
      { key: "link-blue", hex: "#0075de" },
      { key: "link-blue-pressed", hex: "#005bab" },
      { key: "brand-orange", hex: "#dd5b00" },
      { key: "brand-orange-deep", hex: "#793400" },
      { key: "brand-pink", hex: "#ff64c8" },
      { key: "brand-pink-deep", hex: "#a02e6d" },
      { key: "brand-purple", hex: "#7b3ff2" },
      { key: "brand-purple-300", hex: "#d6b6f6" },
      { key: "brand-purple-800", hex: "#391c57" },
      { key: "brand-teal", hex: "#2a9d99" },
      { key: "brand-green", hex: "#1aae39" },
      { key: "brand-yellow", hex: "#f5d75e" },
      { key: "brand-brown", hex: "#523410" },
      { key: "card-tint-peach", hex: "#ffe8d4" },
      { key: "card-tint-rose", hex: "#fde0ec" },
      { key: "card-tint-mint", hex: "#d9f3e1" },
      { key: "card-tint-lavender", hex: "#e6e0f5" },
      { key: "card-tint-sky", hex: "#dcecfa" },
      { key: "card-tint-yellow", hex: "#fef7d6" },
      { key: "card-tint-yellow-bold", hex: "#f9e79f" },
      { key: "card-tint-cream", hex: "#f8f5e8" },
      { key: "card-tint-gray", hex: "#f0eeec" },
      { key: "canvas", hex: "#ffffff" },
      { key: "surface", hex: "#f6f5f4" },
      { key: "surface-soft", hex: "#fafaf9" },
      { key: "hairline", hex: "#e5e3df" },
      { key: "hairline-soft", hex: "#ede9e4" },
      { key: "hairline-strong", hex: "#c8c4be" },
      { key: "ink-deep", hex: "#000000" },
      { key: "ink", hex: "#1a1a1a" },
      { key: "charcoal", hex: "#37352f" },
      { key: "slate", hex: "#5d5b54" },
      { key: "steel", hex: "#787671" },
      { key: "stone", hex: "#a4a097" },
      { key: "muted", hex: "#bbb8b1" },
      { key: "on-dark", hex: "#ffffff" },
      { key: "on-dark-muted", hex: "#a4a097" },
      { key: "semantic-success", hex: "#1aae39" },
      { key: "semantic-warning", hex: "#dd5b00" },
      { key: "semantic-error", hex: "#e03131" },
    ],
    fonts: [{ role: "display and body", family: "Notion Sans" }],
    radius: "xs: 4px; sm: 6px; md: 8px; lg: 12px; xl: 16px; xxl: 20px; xxxl: 24px; full: 9999px",
    spacing: "xxs: 4px · xs: 8px · sm: 12px · md: 16px · lg: 20px · xl: 24px · xxl: 32px · xxxl: 40px · section-sm: 48px · section: 64px · section-lg: 96px · hero: 120px",
    shadow: "rgba(15, 15, 15, 0.2) 0px 24px 48px -8px",
    components: [
      "button-primary",
      "button-dark",
      "button-secondary",
      "button-on-dark",
      "card-base",
      "card-feature",
      "card-feature-yellow-bold",
      "card-feature-peach",
      "card-feature-rose",
      "card-feature-mint",
      "card-feature-sky",
      "card-feature-lavender",
      "workspace-mockup-card",
      "pricing-card",
      "pricing-card-featured",
      "badge-purple",
      "hero-band-dark",
      "stat-row",
      "footer-region",
    ],
  },
  {
    slug: "spotify",
    name: "Spotify",
    description:
      "Spotify's web interface is a dark, immersive music player that wraps listeners in a near-black cocoon (#121212, #181818, #1f1f1f) where album art and content become the primary source of color. The design philosophy is content-first darkness — the UI recedes into shadow so that music, podcasts, and playlists can glow.",
    colors: [
      { key: "spotify-green", hex: "#1ed760" },
      { key: "near-black", hex: "#121212" },
      { key: "dark-surface", hex: "#181818" },
      { key: "mid-dark", hex: "#1f1f1f" },
      { key: "white", hex: "#ffffff" },
      { key: "silver", hex: "#b3b3b3" },
      { key: "near-white", hex: "#cbcbcb" },
      { key: "light", hex: "#fdfdfd" },
      { key: "negative-red", hex: "#f3727f" },
      { key: "warning-orange", hex: "#ffa42b" },
      { key: "announcement-blue", hex: "#539df5" },
      { key: "dark-card", hex: "#252525" },
      { key: "mid-card", hex: "#272727" },
      { key: "border-gray", hex: "#4d4d4d" },
      { key: "light-border", hex: "#7c7c7c" },
      { key: "separator", hex: "#b3b3b3" },
      { key: "light-surface", hex: "#eeeeee" },
      { key: "spotify-green-border", hex: "#1db954" },
    ],
    fonts: [
      {
        role: "title",
        family: "SpotifyMixUITitle, CircularSp-Arab, CircularSp-Hebr, CircularSp-Cyrl, CircularSp-Grek, CircularSp-Deva, Helvetica Neue, helvetica, arial, sans-serif",
      },
      {
        role: "body",
        family: "SpotifyMixUI, CircularSp-Arab, CircularSp-Hebr, CircularSp-Cyrl, CircularSp-Grek, CircularSp-Deva, Helvetica Neue, helvetica, arial, sans-serif",
      },
    ],
    radius: "badge: 2px; input: 4px; card: 6px; section: 8px; large-pill: 500px; pill: 9999px; circle: 50%",
    spacing: "base unit: 8px · scale: 1px, 2px, 3px, 4px, 5px, 6px, 8px, 10px, 12px, 14px, 15px, 16px, 20px",
    shadow: "rgba(0,0,0,0.3) 0px 8px 8px",
    components: [
      "dark-pill",
      "dark-large-pill",
      "light-pill",
      "outlined-pill",
      "circular-play",
      "dark-card",
      "search-input",
      "sidebar",
      "album-grid",
      "now-playing-bar",
    ],
  },
  {
    slug: "uber",
    name: "Uber-Inspired-design-analysis",
    description:
      "An inspired interpretation of Uber's design language — a transportation-and-delivery super-app brand whose web surface is a black-and-white duet, framed by a custom geometric display sans, accented by a single signature pill shape (radius 999px) on every interactive element, and decorated only by editorial 4:3 illustrations of riders, drivers, and city objects.",
    colors: [
      { key: "primary", hex: "#000000" },
      { key: "on-primary", hex: "#ffffff" },
      { key: "ink", hex: "#000000" },
      { key: "body", hex: "#5e5e5e" },
      { key: "mute", hex: "#afafaf" },
      { key: "hairline-mid", hex: "#4b4b4b" },
      { key: "canvas", hex: "#ffffff" },
      { key: "canvas-soft", hex: "#efefef" },
      { key: "canvas-softer", hex: "#f3f3f3" },
      { key: "surface-pressed", hex: "#e2e2e2" },
      { key: "link", hex: "#0000ee" },
      { key: "on-dark", hex: "#ffffff" },
      { key: "black-elevated", hex: "#282828" },
    ],
    fonts: [
      { role: "display", family: "UberMove, UberMoveText, system-ui, Helvetica Neue, Arial, sans-serif" },
      { role: "body", family: "UberMoveText, system-ui, Helvetica Neue, Arial, sans-serif" },
    ],
    radius: "none: 0px; md: 8px; lg: 12px; xl: 16px; pill: 999px; pill-tab: 36px; full: 9999px",
    spacing: "xxs: 4px · xs: 6px · sm: 8px · md: 12px · lg: 16px · xl: 20px · 2xl: 24px · 3xl: 32px",
    shadow: "rgba(0, 0, 0, 0.12) 0px 4px 16px 0px",
    components: [
      "nav-bar",
      "button-primary",
      "button-secondary",
      "button-subtle",
      "button-floating",
      "card-content",
      "card-elevated",
      "card-soft-tinted",
      "promo-card-illustrated",
      "promo-card-on-dark",
      "request-form-card",
      "category-button",
      "hero-band-light",
      "hero-band-dark",
      "showcase-image-card",
      "footer",
    ],
  },
  {
    slug: "airbnb",
    name: "Airbnb-design-analysis",
    description:
      "A warm, generous consumer marketplace anchored on a clean white canvas and Airbnb Rausch (#ff385c), the single brand voltage that carries every primary CTA, search-button orb, and rating dot. Type runs Airbnb Cereal VF at modest weights — display sits at 22–28px in weight 500/600 rather than the heavy 700+ that fintech and enterprise systems use; the brand trusts photography and generous whitespace over typographic muscle. Three product entries (Homes, Experiences, Services) sit in the top nav with hand-illustrated 32-icon glyphs and NEW badges, signaling a marketplace expansion rather than a feature dump. Pill-shaped search bars, softly rounded property cards, and 32px button radii read as friendly and human — there is no hard corner anywhere except the body grid.",
    colors: [
      { key: "primary", hex: "#ff385c" },
      { key: "primary-active", hex: "#e00b41" },
      { key: "primary-disabled", hex: "#ffd1da" },
      { key: "primary-error-text", hex: "#c13515" },
      { key: "primary-error-text-hover", hex: "#b32505" },
      { key: "luxe", hex: "#460479" },
      { key: "plus", hex: "#92174d" },
      { key: "ink", hex: "#222222" },
      { key: "body", hex: "#3f3f3f" },
      { key: "muted", hex: "#6a6a6a" },
      { key: "muted-soft", hex: "#929292" },
      { key: "hairline", hex: "#dddddd" },
      { key: "hairline-soft", hex: "#ebebeb" },
      { key: "border-strong", hex: "#c1c1c1" },
      { key: "canvas", hex: "#ffffff" },
      { key: "surface-soft", hex: "#f7f7f7" },
      { key: "surface-card", hex: "#ffffff" },
      { key: "surface-strong", hex: "#f2f2f2" },
      { key: "on-primary", hex: "#ffffff" },
      { key: "on-dark", hex: "#ffffff" },
      { key: "legal-link", hex: "#428bff" },
      { key: "star-rating", hex: "#222222" },
      { key: "scrim", hex: "#000000" },
    ],
    fonts: [
      { role: "display and body", family: "'Airbnb Cereal VF', Circular, -apple-system, system-ui, Roboto, 'Helvetica Neue', sans-serif" },
    ],
    radius: "none: 0px; xs: 4px; sm: 8px; md: 14px; lg: 20px; xl: 32px; full: 9999px",
    spacing: "xxs: 2px · xs: 4px · sm: 8px · md: 12px · base: 16px · lg: 24px · xl: 32px · xxl: 48px · section: 64px",
    shadow: "rgba(0, 0, 0, 0.02) 0 0 0 1px, rgba(0, 0, 0, 0.04) 0 2px 6px 0, rgba(0, 0, 0, 0.1) 0 4px 8px 0",
    components: [
      "button-primary",
      "button-secondary",
      "button-pill-rausch",
      "search-orb",
      "top-nav",
      "search-bar-pill",
      "search-field-segment",
      "property-card",
      "property-card-photo",
      "experience-card",
      "guest-favorite-badge",
      "reservation-card",
      "date-picker-day-selected",
      "footer-light",
    ],
  },
  {
    slug: "figma",
    name: "Figma-design-analysis",
    description:
      "A confident black-and-white editorial frame interrupted by oversized, hand-cut pastel color blocks. The marketing canvas is rigorously monochrome — figmaSans variable type, pure white surfaces, pure black ink, pill-shaped CTAs — while each story section drops the page into a saturated lime, lavender, cream, mint, or pink panel that reads like a sticky note placed on a clean desk. The result is a design system that feels both technical and joyful — a tool for serious work, made by people who like color.",
    colors: [
      { key: "primary", hex: "#000000" },
      { key: "on-primary", hex: "#ffffff" },
      { key: "ink", hex: "#000000" },
      { key: "canvas", hex: "#ffffff" },
      { key: "inverse-canvas", hex: "#000000" },
      { key: "inverse-ink", hex: "#ffffff" },
      { key: "on-inverse-soft", hex: "#ffffff" },
      { key: "hairline", hex: "#e6e6e6" },
      { key: "hairline-soft", hex: "#f1f1f1" },
      { key: "surface-soft", hex: "#f7f7f5" },
      { key: "block-lime", hex: "#dceeb1" },
      { key: "block-lilac", hex: "#c5b0f4" },
      { key: "block-cream", hex: "#f4ecd6" },
      { key: "block-pink", hex: "#efd4d4" },
      { key: "block-mint", hex: "#c8e6cd" },
      { key: "block-coral", hex: "#f3c9b6" },
      { key: "block-navy", hex: "#1f1d3d" },
      { key: "accent-magenta", hex: "#ff3d8b" },
      { key: "semantic-success", hex: "#1ea64a" },
      { key: "overlay-scrim", hex: "#000000" },
    ],
    fonts: [
      { role: "display and body", family: "figmaSans" },
      { role: "mono", family: "figmaMono" },
    ],
    radius: "xs: 2px; sm: 6px; md: 8px; lg: 24px; xl: 32px; pill: 50px; full: 9999px",
    spacing: "hair: 1px · xxs: 4px · xs: 8px · sm: 12px · md: 16px · lg: 24px · xl: 32px · xxl: 48px · section: 96px",
    shadow: "0 4px 16px rgba(0,0,0,0.06)",
    components: [
      "button-primary",
      "button-secondary",
      "button-tertiary-text",
      "button-magenta-promo",
      "pricing-card",
      "color-block-section",
      "color-block-section-lilac",
      "color-block-section-navy",
      "promo-banner-lilac",
      "template-card",
      "feature-illustration-tile",
      "top-nav",
      "marquee-strip",
      "footer",
    ],
  },
  {
    slug: "claude",
    name: "Claude-design-analysis",
    description:
      "A warm-canvas editorial interface for Anthropic's Claude product. The system anchors on a tinted cream canvas with serif display headlines, warm coral CTAs, and dark navy product surfaces (code editor mockups, model showcase cards). Brand voltage comes from the cream/coral pairing — deliberately warm and humanist where most AI brands use cool blue + slate. Type voice runs a slab-serif display (Copernicus / Tiempos Headline) for h1/h2 and a humanist sans for body. The signature Anthropic black-radial-spike mark anchors the wordmark.",
    colors: [
      { key: "primary", hex: "#cc785c" },
      { key: "primary-active", hex: "#a9583e" },
      { key: "primary-disabled", hex: "#e6dfd8" },
      { key: "ink", hex: "#141413" },
      { key: "body", hex: "#3d3d3a" },
      { key: "body-strong", hex: "#252523" },
      { key: "muted", hex: "#6c6a64" },
      { key: "muted-soft", hex: "#8e8b82" },
      { key: "hairline", hex: "#e6dfd8" },
      { key: "hairline-soft", hex: "#ebe6df" },
      { key: "canvas", hex: "#faf9f5" },
      { key: "surface-soft", hex: "#f5f0e8" },
      { key: "surface-card", hex: "#efe9de" },
      { key: "surface-cream-strong", hex: "#e8e0d2" },
      { key: "surface-dark", hex: "#181715" },
      { key: "surface-dark-elevated", hex: "#252320" },
      { key: "surface-dark-soft", hex: "#1f1e1b" },
      { key: "on-primary", hex: "#ffffff" },
      { key: "on-dark", hex: "#faf9f5" },
      { key: "on-dark-soft", hex: "#a09d96" },
      { key: "accent-teal", hex: "#5db8a6" },
      { key: "accent-amber", hex: "#e8a55a" },
      { key: "success", hex: "#5db872" },
      { key: "warning", hex: "#d4a017" },
      { key: "error", hex: "#c64545" },
    ],
    fonts: [
      { role: "display", family: "Copernicus, Tiempos Headline, serif" },
      { role: "body", family: "StyreneB, Inter, sans-serif" },
      { role: "mono", family: "JetBrains Mono, ui-monospace, monospace" },
    ],
    radius: "xs: 4px; sm: 6px; md: 8px; lg: 12px; xl: 16px; pill: 9999px; full: 9999px",
    spacing: "xxs: 4px · xs: 8px · sm: 12px · md: 16px · lg: 24px · xl: 32px · xxl: 48px · section: 96px",
    shadow: "0 1px 3px rgba(20,20,19,0.08)",
    components: [
      "top-nav",
      "button-primary",
      "button-secondary",
      "button-secondary-on-dark",
      "hero-band",
      "hero-illustration-card",
      "feature-card",
      "product-mockup-card-dark",
      "code-window-card",
      "model-comparison-card",
      "pricing-tier-card",
      "callout-card-coral",
      "badge-coral",
      "cta-band-dark",
      "footer",
    ],
  },
];
